### ISSUE TITLE
A3C: Questions

### ISSUE THREAD

**Issue by IbrahimSobh** [awjuliani/DeepRL-Agents#13]
Dear Juliani

Excellent work!

I would like to know for how long you trained the A3C? and Number of frames used?

How do you find your your results compared to the original paper?   (Denny code did Not achieve the results of the original paper)

Did you  use the same A3C code for Atari games(openai/gym)? Is it easy to be done?

In case of breakout Atari game, do we still need the LSTM layer? and why?

Regards

**Comment by awjuliani** [comment]
Hi Ibrahim,

1. The amount of training time depends on the task at hand. Simple tasks would train very quickly (minutes), while more complex tasks may take days of training.

2. I haven't attempted to reproduce the results of the Mnih paper. However, I expect like Denny that without a large amount of hyperparameter optimization it would be difficult to achieve the results provided in their paper. I would instead recommend attempting to optimize for your own task, rather than for the ALE.

3. Reusing the A3C code for ALE or openAI gym is really simple, as I have built it to be modular.

4. The LSTM layer captures temporal dependencies. Any situation in which there are temporal dependencies you will either need an RNN layer, or stack enough frames to capture all the dynamics of the environment.
